import type {
  Banner,
  Product,
  IngredientGuide,
  CategoryItem,
} from "@/types/models";

export const banners: Banner[] = [
  {
    id: 1,
    title: "다이어트 보조제 신규 입점 EVENT",
    imageUrl: "",
    linkUrl: "/banners/1",
  },
  {
    id: 2,
    title: "이번 주 BEST 후기 모음",
    imageUrl: "",
    linkUrl: "/banners/2",
  },
  {
    id: 3,
    title: "성분별 추천 가이드",
    imageUrl: "",
    linkUrl: "/banners/3",
  },
  {
    id: 4,
    title: "여름 다이어트 챌린지",
    imageUrl: "",
    linkUrl: "/banners/4",
  },
  {
    id: 5,
    title: "신규 가입 혜택",
    imageUrl: "",
    linkUrl: "/banners/5",
  },
];

export const rankingProducts: Product[] = [
  {
    id: 1,
    name: "가르시니아 컷",
    companyName: "헬스랩",
    imageUrl: "",
    rating: 4.8,
    reviewCount: 1245,
    rank: 1,
  },
  {
    id: 2,
    name: "프리미엄 CLA",
    companyName: "뉴트리원",
    imageUrl: "",
    rating: 4.6,
    reviewCount: 982,
    rank: 2,
  },
  {
    id: 3,
    name: "L-카르니틴 600",
    companyName: "비타맥스",
    imageUrl: "",
    rating: 4.5,
    reviewCount: 754,
    rank: 3,
  },
  {
    id: 4,
    name: "그린티 EGCG",
    companyName: "내츄럴팜",
    imageUrl: "",
    rating: 4.4,
    reviewCount: 689,
    rank: 4,
  },
  {
    id: 5,
    name: "사프란 추출물",
    companyName: "퓨어바디",
    imageUrl: "",
    rating: 4.3,
    reviewCount: 542,
    rank: 5,
  },
  {
    id: 6,
    name: "공액리놀레산 1000",
    companyName: "헬스랩",
    imageUrl: "",
    rating: 4.3,
    reviewCount: 487,
    rank: 6,
  },
  {
    id: 7,
    name: "크롬 피콜리네이트",
    companyName: "뉴트리원",
    imageUrl: "",
    rating: 4.2,
    reviewCount: 421,
    rank: 7,
  },
  {
    id: 8,
    name: "포스콜린 250",
    companyName: "비타맥스",
    imageUrl: "",
    rating: 4.2,
    reviewCount: 398,
    rank: 8,
  },
  {
    id: 9,
    name: "라즈베리 케톤",
    companyName: "내츄럴팜",
    imageUrl: "",
    rating: 4.1,
    reviewCount: 356,
    rank: 9,
  },
  {
    id: 10,
    name: "글루코만난 캡슐",
    companyName: "퓨어바디",
    imageUrl: "",
    rating: 4.1,
    reviewCount: 312,
    rank: 10,
  },
  {
    id: 11,
    name: "그린커피빈",
    companyName: "헬스랩",
    imageUrl: "",
    rating: 4.0,
    reviewCount: 287,
    rank: 11,
  },
  {
    id: 12,
    name: "프로바이오틱스 슬림",
    companyName: "뉴트리원",
    imageUrl: "",
    rating: 4.0,
    reviewCount: 254,
    rank: 12,
  },
];

export const ingredientGuides: IngredientGuide[] = [
  { id: 1, name: "가르시니아" },
  { id: 2, name: "CLA" },
  { id: 3, name: "L-카르니틴" },
  { id: 4, name: "그린티 추출물" },
  { id: 5, name: "사프란" },
  { id: 6, name: "크롬" },
  { id: 7, name: "포스콜린" },
  { id: 8, name: "라즈베리 케톤" },
  { id: 9, name: "글루코만난" },
  { id: 10, name: "그린커피빈" },
  { id: 11, name: "프로바이오틱스" },
];

export const categoryItems: CategoryItem[] = [
  { id: 1, name: "체지방 감소", linkUrl: "/products?category=fat-loss" },
  { id: 2, name: "탄수화물 컷", linkUrl: "/products?category=carb-cut" },
  { id: 3, name: "포만감 증가", linkUrl: "/products?category=satiety" },
  { id: 4, name: "에너지 부스터", linkUrl: "/products?category=energy" },
  { id: 5, name: "유산균/장건강", linkUrl: "/products?category=probiotics" },
  { id: 6, name: "단백질", linkUrl: "/products?category=protein" },
];
